# Generated by Django 4.0.5 on 2022-08-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='seguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NUMERO_DOCUMENTO', models.CharField(max_length=30)),
                ('ID_ACTIVIDAD', models.CharField(max_length=30)),
                ('ID_CURSO_DE_VIDA', models.CharField(max_length=30)),
                ('EDAD', models.CharField(max_length=30)),
            ],
        ),
    ]
